include: package:lints/recommended.yaml

# Uncomment the following section to specify additional rules.


analyzer:
  exclude:
    - build/**
    - packages/**
linter:
  rules:
    - camel_case_types: true
    - file_names: false
    - constant_identifier_names: false
    - no_leading_underscores_for_local_identifiers: false
    - non_constant_identifier_names: false
