name: zeniqswap_backend
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0
  shelf_cors_headers: ^0.1.5
  collection: ^1.19.0
  http: ^1.4.0
  walletkit_dart:
    path: packages/walletkit-dart

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.5
  lints: ^2.0.0
