name: Backend CI/CD

on:
  push:
    branches: ["main"]
    tags:
      - "v*"
  pull_request:
    branches: ["main"]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.4"
          channel: "stable"
          cache: true
      - run: git submodule update --init --recursive
      - run: flutter pub get
      - name: Lint analysis
        continue-on-error: true
        run: flutter analyze

  build-and-deploy-staging:
    name: Build and Deploy Staging
    runs-on: ubuntu-latest
    needs: lint
    if: startsWith(github.ref, 'refs/tags/vi')
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.4"
          channel: "stable"
          cache: true
      - run: git submodule update --init --recursive
      - run: flutter pub get

      - name: activate frog cli
        run: dart pub global activate dart_frog_cli

      - name: build frog
        run: dart_frog build

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Add staging server to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.HOST_STAGING}} >> ~/.ssh/known_hosts

      - name: Test staging SSH connection
        run: |
          ssh -v -i ~/.ssh/id_ed25519 ${{ secrets.USERNAME }}@${{ secrets.HOST_STAGING }} "echo 'SSH connection established'"

      - name: rsync to staging server
        run: rsync -avz --delete --exclude='.git' build/ ${{ secrets.USERNAME }}@${{ secrets.HOST_STAGING }}:zeniqswap_backend/

      - name: Build Docker image on staging server
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.USERNAME }}@${{ secrets.HOST_STAGING }} "\
            cd zeniqswap_backend && \
            docker build . -t zeniqswap_backend"

      - name: Stop and remove old container on Staging server
        if: always()
        continue-on-error: true
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.USERNAME }}@${{ secrets.HOST_STAGING }} "\
            echo 'Stopping container...' && \
            (docker stop zeniqswap_backend || true) && \
            (docker rm -f zeniqswap_backend || true) && \
            sleep 2 && \
            docker rm -f $(docker ps -a -q --filter 'name=zeniqswap_backend') || true && \
            docker rm -f $(docker ps -a -q --filter 'status=dead') || true && \
            docker rm -f $(docker ps -a -q --filter 'status=exited') || true && \
            echo 'Cleanup complete'"
      
      - name: Prune unused Docker resources on Staging server
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.USERNAME }}@${{ secrets.HOST_STAGING }} "docker system prune -f"

      - name: Start new container on staging server
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.USERNAME }}@${{ secrets.HOST_STAGING }} "\
            echo 'Starting new container...' && \
            docker run -d \
              --init \
              --name zeniqswap_backend \
              --restart unless-stopped \
              -p 8080:8080 \
              -e VERSION=${{github.ref_name}} \
              zeniqswap_backend || exit 1 && \
            echo 'Container started successfully'"

      - name: Verify deployment on staging server
        if: always()
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.USERNAME }}@${{ secrets.HOST_STAGING }} "\
            echo 'Docker container status:' && \
            if docker ps | grep -q zeniqswap_backend; then \
              echo 'Container is running' && \
              docker ps | grep zeniqswap_backend; \
            else \
              echo 'Warning: Container not found'; \
            fi
          "
      

  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    needs: lint
    if: startsWith(github.ref, 'refs/tags/') && !startsWith(github.ref, 'refs/tags/vi')
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.4"
          channel: "stable"
          cache: true
      - run: git submodule update --init --recursive
      - run: flutter pub get

      - name: activate frog cli
        run: dart pub global activate dart_frog_cli

      - name: build frog
        run: dart_frog build

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Add LIQ server to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.HOSTLIQ }} >> ~/.ssh/known_hosts

      - name: Test LIQ SSH connection
        run: |
          ssh -v -i ~/.ssh/id_ed25519 ${{ secrets.USERNAME }}@${{ secrets.HOSTLIQ }} "echo 'SSH connection established'"

      - name: Add DEX server to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.HOSTDEX }} >> ~/.ssh/known_hosts

      - name: Test DEX SSH connection
        run: |
          ssh -v -i ~/.ssh/id_ed25519 ${{ secrets.USERNAME }}@${{ secrets.HOSTDEX }} "echo 'SSH connection established'"

      - name: rsync to liquidity server
        run: rsync -avz --delete --exclude='.git' build/ ${{ secrets.USERNAME }}@${{ secrets.HOSTLIQ }}:zeniqswap_backend/

      - name: rsync to dex server
        run: rsync -avz --delete --exclude='.git' build/ ${{ secrets.USERNAME }}@${{ secrets.HOSTDEX }}:zeniqswap_backend/

      - name: Build Docker image on LIQ server
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.USERNAME }}@${{ secrets.HOSTLIQ }} "\
            cd zeniqswap_backend && \
            docker build . -t zeniqswap_backend"

      - name: Stop and remove old container on LIQ server
        if: always()
        continue-on-error: true
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.USERNAME }}@${{ secrets.HOSTLIQ }} "\
            echo 'Stopping container...' && \
            (docker stop zeniqswap_backend || true) && \
            (docker rm -f zeniqswap_backend || true) && \
            sleep 2 && \
            docker rm -f $(docker ps -a -q --filter 'name=zeniqswap_backend') || true && \
            docker rm -f $(docker ps -a -q --filter 'status=dead') || true && \
            docker rm -f $(docker ps -a -q --filter 'status=exited') || true && \
            echo 'Cleanup complete'"

      - name: Prune unused Docker resources on LIQ server
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.USERNAME }}@${{ secrets.HOSTLIQ }} "docker system prune -f"

      - name: Start new container on LIQ server
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.USERNAME }}@${{ secrets.HOSTLIQ }} "\
            echo 'Starting new container...' && \
            docker run -d \
              --init \
              --name zeniqswap_backend \
              --restart unless-stopped \
              -p 8080:8080 \
              -e VERSION=${{ github.ref_name }} \
              zeniqswap_backend || exit 1 && \
            echo 'Container started successfully'"

      - name: Verify deployment on LIQ server
        if: always()
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.USERNAME }}@${{ secrets.HOSTLIQ }} "\
            echo 'Docker container status:' && \
            if docker ps | grep -q zeniqswap_backend; then \
              echo 'Container is running' && \
              docker ps | grep zeniqswap_backend; \
            else \
              echo 'Warning: Container not found'; \
            fi
          "

      - name: Build Docker image on DEX server
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.USERNAME }}@${{ secrets.HOSTDEX }} "\
            cd zeniqswap_backend && \
            docker build . -t zeniqswap_backend"

      - name: Stop and remove old container on DEX server
        if: always()
        continue-on-error: true
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.USERNAME }}@${{ secrets.HOSTDEX }} "\
            echo 'Stopping container...' && \
            (docker stop zeniqswap_backend || true) && \
            (docker rm -f zeniqswap_backend || true) && \
            sleep 2 && \
            docker rm -f $(docker ps -a -q --filter 'name=zeniqswap_backend') || true && \
            docker rm -f $(docker ps -a -q --filter 'status=dead') || true && \
            docker rm -f $(docker ps -a -q --filter 'status=exited') || true && \
            echo 'Cleanup complete'"

      - name: Prune unused Docker resources on DEX server
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.USERNAME }}@${{ secrets.HOSTDEX }} "docker system prune -f"

      - name: Start new container on DEX server
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.USERNAME }}@${{ secrets.HOSTDEX }} "\
            echo 'Starting new container...' && \
            docker run -d \
            --init \
            --name zeniqswap_backend \
            --restart unless-stopped \
            -p 8080:8080 \
            -e VERSION=${{ github.ref_name }} \
            zeniqswap_backend || exit 1 && \
            echo 'Container started successfully'"

      - name: Verify deployment on DEX server
        if: always()
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.USERNAME }}@${{ secrets.HOSTDEX }} "\
            echo 'Docker container status:' && \
            if docker ps | grep -q zeniqswap_backend; then \
              echo 'Container is running' && \
              docker ps | grep zeniqswap_backend; \
            else \
              echo 'Warning: Container not found'; \
            fi
          "