name: Backend CI/CD

on:
  push:
    branches: ["main"]
    tags:
      - "v*"
  pull_request:
    branches: ["main"]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v1
      - run: git submodule update --init --recursive
      - run: flutter pub get
      - name: Lint analysis
        continue-on-error: true
        run: flutter analyze

  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    needs: lint
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v1
      - run: git submodule update --init --recursive
      - run: flutter pub get

      - name: activate frog cli
        run: dart pub global activate dart_frog_cli

      - name: build frog
        run: dart_frog build

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Add LIQ server to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.HOSTLIQ }} >> ~/.ssh/known_hosts

      - name: Test LIQ SSH connection
        run: |
          ssh -v -i ~/.ssh/id_ed25519 ${{ secrets.USERNAME }}@${{ secrets.HOSTLIQ }} "echo 'SSH connection established'"

      - name: Add DEX server to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.HOSTDEX }} >> ~/.ssh/known_hosts

      - name: Test DEX SSH connection
        run: |
          ssh -v -i ~/.ssh/id_ed25519 ${{ secrets.USERNAME }}@${{ secrets.HOSTDEX }} "echo 'SSH connection established'"

      - name: rsync to liquidity server
        run: rsync -avz --delete --exclude='.git' build/ ${{ secrets.USERNAME }}@${{ secrets.HOSTLIQ }}:zeniqswap_backend/

      - name: rsync to dex server
        run: rsync -avz --delete --exclude='.git' build/ ${{ secrets.USERNAME }}@${{ secrets.HOSTDEX }}:zeniqswap_backend/

      #   - name: build docker image on LIQ server
      #     run: ssh -i ~/.ssh/id_ed25519 ${{ secrets.USERNAME }}@${{ secrets.HOSTLIQ }} "cd zeniqswap_backend && docker build . -t zeniqswap_backend && docker rm -f zeniqswap_backend && docker ps -a | grep zeniqswap_backend && systemctl restart zeniqswap-backend.service"
      - name: Build Docker image on LIQ server
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.USERNAME }}@${{ secrets.HOSTLIQ }} "\
            cd zeniqswap_backend && \
            docker build . -t zeniqswap_backend"

      - name: Stop old container on LIQ server
        if: always()
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.USERNAME }}@${{ secrets.HOSTLIQ }} "\
            docker rm -f zeniqswap_backend || true"

      - name: Restart service on LIQ server
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.USERNAME }}@${{ secrets.HOSTLIQ }} "\
            sudo systemctl restart zeniqswap-backend.service"

      - name: Verify deployment on LIQ server
        if: always()
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.USERNAME }}@${{ secrets.HOSTLIQ }} "\
            echo 'Docker container status:' && \
            if docker ps | grep -q zeniqswap_backend; then \
              echo 'Container is running' && \
              docker ps | grep zeniqswap_backend; \
            else \
              echo 'Warning: Container not found'; \
            fi && \
            echo 'Service status:' && \
            if systemctl is-active --quiet zeniqswap-backend.service; then \
              echo 'Service is active' && \
              systemctl status zeniqswap-backend.service; \
            else \
              echo 'Warning: Service is not active'; \
            fi"

      - name: Build Docker image on DEX server
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.USERNAME }}@${{ secrets.HOSTDEX }} "\
            cd zeniqswap_backend && \
            docker build . -t zeniqswap_backend"

      - name: Stop old container on DEX server
        if: always()
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.USERNAME }}@${{ secrets.HOSTDEX }} "\
            docker rm -f zeniqswap_backend || true"

      - name: Restart service on DEX server
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.USERNAME }}@${{ secrets.HOSTDEX }} "\
            sudo systemctl restart zeniqswap-backend.service"
            - name: Verify deployment on LIQ server
            if: always()
            run: |
              ssh -i ~/.ssh/id_ed25519 ${{ secrets.USERNAME }}@${{ secrets.HOSTDEX }} "\
                echo 'Docker container status:' && \
                if docker ps | grep -q zeniqswap_backend; then \
                  echo 'Container is running' && \
                  docker ps | grep zeniqswap_backend; \
                else \
                  echo 'Warning: Container not found'; \
                fi && \
                echo 'Service status:' && \
                if systemctl is-active --quiet zeniqswap-backend.service; then \
                  echo 'Service is active' && \
                  systemctl status zeniqswap-backend.service; \
                else \
                  echo 'Warning: Service is not active'; \
                fi"
