name: Backend CI/CD

on:
  push:
    branches: ["main"]
    tags:
      - "v*"
  pull_request:
    branches: ["main"]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v1
      - run: git submodule update --init --recursive
      - run: flutter pub get
      - name: Lint analysis
        run: flutter analyze

  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    needs: lint
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v1
      - run: git submodule update --init --recursive
      - run: flutter pub get

      - name: activate frog cli
        run: dart pub activate dart_frog_cli

      - name: build frog
        run: dart frog build

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Add LIQ server to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.HOSTLIQ }} >> ~/.ssh/known_hosts

      - name: Test LIQ SSH connection
        run: |
          ssh -v -i ~/.ssh/id_ed25519 ${{ secrets.USERNAME }}@${{ secrets.HOSTLIQ }} "echo 'SSH connection established'"

      - name: Add DEX server to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.HOSTDEX }} >> ~/.ssh/known_hosts

      - name: Test DEX SSH connection
        run: |
          ssh -v -i ~/.ssh/id_ed25519 ${{ secrets.USERNAME }}@${{ secrets.HOSTDEX }} "echo 'SSH connection established'"

    #   - name: rsync to liquidity server
    #     run: rsync -avz --delete --exclude='.git' build/ ${{ secrets.USERNAME }}@${{ secrets.HOSTLIQ }}:zeniqswap_backend/

    #   - name: rsync to dex server
    #     run: rsync -avz --delete --exclude='.git' build/ ${{ secrets.USERNAME }}@${{ secrets.HOSTDEX }}:zeniqswap_backend/
